name: SAP CF APP保活

on:
  schedule:
    - cron: "*/5 * * * *"
    - cron: "*/10 * * * *"
    - cron: "*/15 * * * *"
    - cron: "*/20 * * * *"
    - cron: "*/30 * * * *"
  workflow_dispatch:

concurrency:
  group: keepalive
  cancel-in-progress: true

jobs:
  keepalive-app1:
    runs-on: ubuntu-latest
    timeout-minutes: 8

    steps:
      - name: KeepAlive APP1
        uses: docker://ghcr.io/uncleluogithub/cf-keepalive:latest
        env:
          CF_USERNAME: ${{ secrets.CF_USERNAME }}
          CF_PASSWORD: ${{ secrets.CF_PASSWORD }}
          CF_API:      ${{ secrets.CF_API }}
          CF_ORG:      ${{ secrets.CF_ORG }}
          CF_SPACE:    ${{ secrets.CF_SPACE }}
          CF_APP:      ${{ secrets.CF_APP }}
          CF_SET_PROCESS_HC: "true"
          # DEBUG: "1"
          # CF_TRACE: "true"

  keepalive-app2:
    runs-on: ubuntu-latest
    timeout-minutes: 8

    steps:
      - name: KeepAlive APP2
        uses: docker://ghcr.io/uncleluogithub/cf-keepalive:latest
        env:
          CF_USERNAME: ${{ secrets.CF_USERNAME2 }}
          CF_PASSWORD: ${{ secrets.CF_PASSWORD2 }}
          CF_API:      ${{ secrets.CF_API2 }}
          CF_ORG:      ${{ secrets.CF_ORG2 }}
          CF_SPACE:    ${{ secrets.CF_SPACE2 }}
          CF_APP:      ${{ secrets.CF_APP2 }}
          CF_SET_PROCESS_HC: "true"
          # DEBUG: "1"
          # CF_TRACE: "true"

  keepalive-app3:
    runs-on: ubuntu-latest
    timeout-minutes: 8

    steps:
      - name: KeepAlive APP3
        uses: docker://ghcr.io/uncleluogithub/cf-keepalive:latest
        env:
          CF_USERNAME: ${{ secrets.CF_USERNAME3 }}
          CF_PASSWORD: ${{ secrets.CF_PASSWORD3 }}
          CF_API:      ${{ secrets.CF_API3 }}
          CF_ORG:      ${{ secrets.CF_ORG3 }}
          CF_SPACE:    ${{ secrets.CF_SPACE3 }}
          CF_APP:      ${{ secrets.CF_APP3 }}
          CF_SET_PROCESS_HC: "true"
          # DEBUG: "1"
          # CF_TRACE: "true"
